

#Each new term in the Fibonacci sequence is generated by adding the previous two terms.
#By starting with 1 and 2, the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not exceed four million,
#find the sum of the even-valued terms.
total = 2
f_list = [1, 2]

while f_list[-1] + f_list[-2] <= 4000000:
    f_list.append(f_list[-1]+f_list[-2])  #add the sum of the last 2 elements to the list.  This becomes the new last
    if f_list[-1] % 2 == 0: #add to the total if this new element is even
        total += f_list[-1]

#print(len(f_list))
#print(f_list)
print(total)
